### ISSUE TITLE
Changes from abnTeX2

### ISSUE THREAD

**Issue by lucasresck** [lucasmoschen/modelo-tcc-emap#1]
Hello there,

Which were the modifications in relation to the original version from abnTeX2, despite the language?

**Comment by lucasmoschen** [comment]
The idea is to use the rules from FGV. This project is not completed yet, but it will be soon (and I accept contributors!) 
Things that already changed from the file "abntex2-modelo-trabalho-academico.pdf" 

- Cover and cover sheet; 
- Catalog card (library); 
- Dedication. 

The suggested structure may also help others. After finishing everything, it may be a good start for every EMAp student.
