### ISSUE TITLE
Title and Subtitle

### ISSUE THREAD

**Issue by FredsoNerd** [lucasmoschen/modelo-tcc-emap#4]
A good question I imagine some of you guys have already struggled with is about the **title** and **subtitle**. In Overleaf and in my local machine (using texlive), I've got the output as

```
ESTE É O SUBTÍTULO DO MEU TCC: ESTE É O SUBTÍTULO DO MEU TCC
```
instead of
```
ESTE É O TÍTULO DO MEU TCC: ESTE É O SUBTÍTULO DO MEU TCC
```
Any of you got the same problem? If not, I think It's reasonable to remember fixing that! :)

**Comment by FredsoNerd** [comment]
> Any of you got the same problem?

If that's the case, consider the following, replacing the definitions of `\subtitulo` and `\imprimirsubtitulo` in the beginning of the file `capa_folha_rosto.tex` as follows
```tex
\newcommand{\subtitulo}[1]{\title{#1}}
\newcommand{\imprimirsubtitulo}{\thetitle}
```
with the following
```tex
\newcommand\subtitulo[1]{\def\@subtitulo{#1}}
\newcommand{\imprimirsubtitulo}{\@subtitulo}
```
What we're doing is to define a custom variable `\@subtitulo` instead of reusing the functions `\title` and `\thetitle`.

**Comment by lucasmoschen** [comment]
Thanks, @FredsoNerd for the suggestion! It was an unnoticed error.

**Comment by FredsoNerd** [comment]
I'm closing this issue, once the problem seems to be fixed.
